[book]
authors = ["Alan W. Smith"]
language = "en"
multilingual = false
src = "src"
title = "Typing Rust"

[build]
build-dir = "site"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
additional-css = [
  "theme/highlight.min.js",
  "theme/overrides.css",
  "theme/step-by-step-v2.css"
]
additional-js = [
  "theme/typo-detector.js", 
  "theme/step-by-step.js", 
  "theme/step-by-step-v2.js"
]

[output.html.playground]
editable = true
copyable = false 
line-numbers = true

[output.html.search]
enable = false

[output.html.print]
enable = true 

